### ISSUE TITLE
Xpra seccomp error

### ISSUE THREAD

**Issue by willscott** [subgraph/oz#10]
Installation steps worked without obvious errors.
Upon attempting to start evince, I see the following logs from the oz-daemon, at which point it hangs: (oz shell won't let me inspect the crashed container)
```
2015/08/25 08:50:39 [evince] Hostname set to (evince.local)
2015/08/25 08:50:39 [evince] dbus-uuid: b1a8589a47cb53ad533aeaa255dc8ecf
2015/08/25 08:50:39 [evince] xpra work dir is /home/user/.Xoz/evince
2015/08/25 08:50:39 [evince] Starting xpra server
2015/08/25 08:50:39 [evince] (xpra) E Error (seccomp): function not implemented
2015/08/25 08:50:39 [evince] Child process pid=8 exited with status 1
```

I've been able to run xpra directly with a seccomp policy specified.

**Comment by dma** [comment]
Hi Will, what kernel version do you have?

**Comment by willscott** [comment]
```
$ uname -a
Linux w 3.16.0-4-amd64 #1 SMP Debian 3.16.7-ckt11-1 (2015-05-24) x86_64 GNU/Linux
```

**Comment by dma** [comment]
I believe it's failing for you because of go-seccomp's use of the SECCOMP_FILTER_FLAG_TSYNC flag, introduced in 3.17.

**Comment by willscott** [comment]
Updating to
```
Linux w 4.1.0-1-amd64 #1 SMP Debian 4.1.3-1 (2015-08-03) x86_64 GNU/Linux
```
solved the issue.
