### ISSUE TITLE
Improve build support and instructions

### ISSUE THREAD

**Issue by DarkCoridor** [subgraph/oz#117]
When trying to build Oz as standalone after `buildpackage` the process errors out with: 

```
user@host:~/oz$ gbp buildpackage -us -uc
gbp:info: Creating oz-daemon_0.2.4.orig.tar.gz from '0.2.4'
gbp:info: Extracting oz-daemon_0.2.4.orig.tar.gz to '/tmp/build-area/oz-daemon-tmp'
gbp:info: Exporting 'HEAD' to '/tmp/build-area/oz-daemon-tmp'
gbp:info: Moving '/tmp/build-area/oz-daemon-tmp' to '/tmp/build-area/oz-daemon-0.2.4'
Base directory /var/cache/pbuilder/base.cow does not exist
gbp:error: 'git-pbuilder -us -uc' failed: it exited with 1
```

Following the things outlined in pull-request #103 do not help and lead to same error.

Being able to build and test Oz as a standalone would be nice for contributors / testers who do not have a whole SGOS machine.

**Comment by dma** [comment]
Yeah, we've changed that, and the README needs to be updated. Follow these build instructions:

https://github.com/subgraph/subgraph-debian-packages

**Comment by dma** [comment]
Opened an issue for updating our documentation, so closing this.
