### ISSUE TITLE
Automatically fix Xpra clipboard recursion bug. 

### ISSUE THREAD

**Issue by xSmurf** [subgraph/oz#26]
Sometimes Xpra handling of clipboard detects some form of a recursion and disables the clipboard for a sandbox. This should be detected automatically and the clipboard feature toggled back on transparently.

**Comment by xSmurf** [comment]
See also https://github.com/subgraph/subgraph-os-issues/issues/81

**Comment by timthelion** [comment]
Subuser also suffers from this too. Do you know if this is fixed/will be fixed upstream?

**Comment by dma** [comment]
https://github.com/subgraph/oz/commit/320ed99b57fd552273876285c5a3f8686259ef9e.
