### ISSUE TITLE
Expose mount/unmount to the oz cli client. 

### ISSUE THREAD

**Issue by xSmurf** [subgraph/oz#30]
Right now the mount/unmount commands are only exposed on the socket and used by the extension, they should be made available from the oz cli as well.

**Comment by david415** [comment]
work in progress here:
https://github.com/david415/oz/tree/30.add_cli_mount_umount.0

**Comment by david415** [comment]
my implementation needs code review. i've tested it:
https://github.com/subgraph/oz/pull/63

**Comment by david415** [comment]
resolved here:
https://github.com/subgraph/oz/commit/faa6adc68d68f0ab719f386faeb86c09c2d5d345

this ticket should be closed
