### ISSUE TITLE
Default Tor Browser Download Location & Text Rendering

### ISSUE THREAD

**Issue by wiltongorske** [subgraph/oz#32]
When clicking the folder icon on the Downloads page of the Tor Browser, it opens up the Files window where the text is not displaying properly (showing up as tiny boxes--see screenshot). It does appear to be pointing to the correct location, though:

/home/user/.local/share/torbrowser/tbb/x86_64/tor-browser_en-US/Browser/Downloads

![screenshot from 2016-02-04 18-43-20](https://cloud.githubusercontent.com/assets/16182677/12825775/d62a5e24-cb6f-11e5-9b0b-ac22458d6e34.png)
![screenshot from 2016-02-04 18-43-52](https://cloud.githubusercontent.com/assets/16182677/12825774/d60032f2-cb6f-11e5-9b3b-4aaf8457e222.png)

Furthermore, trying to open the file via VLC directly also does not work:

> File reading failed:
> VLC could not open the file "/home/user/.local/share/torbrowser/tbb/x86_64/tor-browser_en-US/Browser/Downloads/32c3-7277-en-de-Breaking_Honeypots_for_Fun_and_Profit_sd.mp4" (No such file or directory).
> Your input can't be opened:
> VLC is unable to open the MRL 'file:///home/user/.local/share/torbrowser/tbb/x86_64/tor-browser_en-US/Browser/Downloads/32c3-7277-en-de-Breaking_Honeypots_for_Fun_and_Profit_sd.mp4'. Check the log for details.

**Comment by xSmurf** [comment]
Thanks for reporting this. I definitely reproduced this. Weirdly on the second launching of the file browser (nautilus) the fonts are fixed and appear normally. I will have to keep investigating.

**Comment by xSmurf** [comment]
Turns out this is a bug with TorBrowser and not OZ.

https://trac.torproject.org/projects/tor/ticket/18813
