### ISSUE TITLE
Opening attachments (PDF) in Icedove doesn't work

### ISSUE THREAD

**Issue by thomwiggers** [subgraph/oz#39]
I thing it is because it tries to launch the sandboxed evince, and this logs into the journal:

    Feb 15 11:36:18 subgraph oz-daemon[765]: 2016/02/15 11:36:18 [icedove] (stderr) Cannot run a sandbox from inside a running sandbox!
 
A workaround is using `/usr/bin-oz/evince` from within icedove.

**Comment by xSmurf** [comment]
Migrated as #56
