### ISSUE TITLE
OZ sandboxed applications fail if /media/user doesn't exist

### ISSUE THREAD

**Issue by dma** [subgraph/oz#43]

**Comment by xSmurf** [comment]
I'm not sure OZ should start messing with random system directories on the host. I wouldn't expect OZ to create a $HOME if it were missing. I can make it not fail, but that sandbox will be unable to mount files from external mounts which, while maybe less annoying, is a failure in itself.

**Comment by xSmurf** [comment]
This has been fixed in the installer itself, closing.
