### ISSUE TITLE
Iceweasel doesn't launch

### ISSUE THREAD

**Issue by boskote** [subgraph/oz#46]
Tried without torbrowser running. Tried restarting oz-daemon. Here is the section of oz log from the attempted launch: https://share.riseup.net/#z_5y8ol4kepDfkx5SUlmug

**Comment by xSmurf** [comment]
This will be fixed once the whitelist is added again.

Or maybe we should consider dropping `unshare` syscall from the default blacklist. What do you think @dma ?

**Comment by xSmurf** [comment]
Superseded via profile repo, iceweasel migration, and no longer relevant, etc etc :)
