### ISSUE TITLE
x-eyes can see were your mouse is even when the mouse is outside of the xeyes window.

### ISSUE THREAD

**Issue by timthelion** [subgraph/oz#5]
Viz demo.

This is an information leak... I guess this needs to be solved on the xpra side of things, as an option obviously.

**Comment by dma** [comment]
Please clarify. In the demo, the following happens:

1. xeyes is launched outside of any sandbox
2. evince is opened
3. the user enters the evince sandbox via oz shell
4. the user starts a second instance of xeyes inside the evince sandbox. 
5. the user moves the mouse around to demonstrate the opposite of what you are claiming.

xeyes in the evince sandbox will connect to the xpra server that evince is already connected to, and is thus able to see and follow the mouse move events that occur within the evince window region as well as its own. If you watch the video carefully you will see precisely where the sandboxed xeyes instance stops seeing mouse events.

The point of running two instances of xeyes was to depict the "firewalling" of X events that Xpra provides vs. running X clients on the host display server.

Is this what you're talking about, or do you see something else?

I'll note that we don't necessarily consider Xpra our target state. We are keeping an eye on Wayland to see how it could work.

**Comment by timthelion** [comment]
Aha, that was not clear to me, that evince and xeyes where within the same sandbox. My appologies.
