### ISSUE TITLE
Assisted (automatic?) generation of seccomp policies

### ISSUE THREAD

**Issue by Fuzion24** [subgraph/oz#54]
In order to avoid having to manually write whitelist seccomp policies for every application you use -- it would be nice to have something like run the application one time through to do a sandboxing generation policy.  It could be something like running strace and parsing the output into a seccomp policy file.

**Comment by dma** [comment]
Hi Fuzion24, we have already implemented this -- though it's a little basic and we plan to improve it further. Try this:

oz-seccomp-tracer -train -output /tmp/ls-whitelist.seccomp /bin/ls 

Note the strace-style output to stderr, that's us, not strace..

This is in fact how we generate our whitelists. We then tweak them by turning off seccomp whitelist enforcement and watching the logs for seccomp hits. See here:

https://github.com/subgraph/oz/wiki/Oz-Seccomp-Non-Enforcement-Mode

**Comment by Fuzion24** [comment]
very cool. thanks for the explanation. keep up the good work. subgraph is looking pretty good =D

**Comment by dma** [comment]
thanks, still lots to do..
