### ISSUE TITLE
oz rpc for dynamic proxy

### ISSUE THREAD

**Issue by david415** [subgraph/oz#66]
**the problem:**
Applications such as Ricochet and Onionshare will need to be able to receive their onion service connections from little-t tor which sits on the host outside of oz. The application will create it's listener but it will be listening inside the oz jail cell and therefore will never receive the connection from the tor process unless we setup a proxy rule for that particular port. We however cannot know in advance which port to proxy because applications like Ricochet typically decide this at run time.

**one possible solution**
We've been planning to deploy roflcoptor as the tor control port filter daemon. Oz profiles for applications like Ricochet will be configured to proxy the tor control port to roflcoptor running outside of oz on the host. This much I have tested: https://github.com/subgraph/oz/pull/65 the Oz tcp-to-unix socket proxy. oz-init creates a TCP listener inside oz that listens on 127.0.0.1 port 9051 which is the default tor control port that these applications use. Outside of oz it proxies to a specific unix domain socket that roflcoptor provisions and listens on with the filter policy for that specific application.

This however isn't enough. Onionshare can for example create it's onion service... however it specifies a port for the tor process to connect and forward to when it receives an onion service connection. The listener for these onion services are in the oz sandbox and therefore will not be able to receive the connection from the tor process unless we specifically configure oz to proxy those connections!

We must add an RPC interface to add and delete proxy rules. Roflcoptor can then use this RPC interface when it receives either an ADD_ONION or DEL_ONION command to create the necessary proxy rules to allow tor to actually connect to the sandboxed application's onion service listener. Initially we can do this with an oz TCP proxy but eventually it would be nice to configured unix domain sockets all the way down.

**Comment by xSmurf** [comment]
Everything for this is now in master and in the 0.1.0 tag! Thanks for the awesome work @david415 :+1: :100: :tada:
