### ISSUE TITLE
Specify in documentation go dependencies

### ISSUE THREAD

**Issue by botherder** [subgraph/oz#7]
I'm going through the process of installing Oz. Just a few note, it should be worth noting that it requires Go >=1.4 and an additional couple of packages.
Right now I'm running Go 1.5, and I had to ```go get github.com/subgraph/go-seccomp``` and golang.org/x/sys/unix before being able to proceed with the install.

**Comment by xSmurf** [comment]
Thanks for the issue report. I've fixed the godeps in b7cf1a6a4ab1592d5b26917910e40059c4f21f30 and added a note about the golang version in the README.
