### ISSUE TITLE
Need to specifiy parameter arguments as filenames to bind mount

### ISSUE THREAD

**Issue by dma** [subgraph/oz#79]
Oz doesn't support Onionshare via Nautilus at the moment due to it being invoked as:

onionshare-gui --filenames [target files]

Oz can't bindmount the files because it can't extract them from the arguments, therefore this feature does not work.

**Comment by xSmurf** [comment]
Could you provide a log? This works fine for Evince and LibreOffice for example...

**Comment by xSmurf** [comment]
Looking at the profile for Onionshare shows that the `allow_files` flag is not set, which would explain why files aren't added.

**Comment by dma** [comment]
Did you try it? I set allow_files locally. The problem as described in the issue is that the filenames only come after the --filenames flag, and they aren't recognized by Oz.

**Comment by xSmurf** [comment]
So the issue was that the Nautilus extension doesn't pass the flag?

**Comment by dma** [comment]
Hmm, yeah, I am wrong, I was testing everything last night to prepare for a demo, --filenames does result in the file getting bind mounted in. What he hell, it totally works now. Sorry for the noise.
