### ISSUE TITLE
Onionshare checking its install location breaks when its executable is diverted.

### ISSUE THREAD

**Issue by dma** [subgraph/oz#80]
onionshare-gui can no longer find resource files at the "expected locatoin" after the Oz divert is setup.

It looks for them in /usr/lib/python3/dist-packages/resources 

Before the divert, they are located correctly at the filesystem locations where they were installed:

/usr/share/onionshare/

This causes Onionshare to crash.

Workaround was to copy everything into:

 /usr/lib/python3/dist-packages/resources

**Comment by xSmurf** [comment]
Why would this be diverted?

This doesn't seem to be a problem for Gajim or TorBrowser-Launcher (two other python apps) or something linked to oz-setup which will only divert the paths specified in the profile...

**Comment by xSmurf** [comment]
The offending bit from upstream:

```
    if p == 'Linux' and sys.argv and sys.argv[0].startswith('/usr/bin/onionshare'):
        # OnionShare is installed systemwide in Linux
        resources_dir = os.path.join(sys.prefix, 'share/onionshare')
```

**Comment by xSmurf** [comment]
I've opened a pull request upstream: https://github.com/micahflee/onionshare/pull/315

**Comment by micahflee** [comment]
Merged! I'll make a new onionshare release soon, hopefully today, with this PR
