### ISSUE TITLE
Fails to set up sandbox if `/media/$USER` does not exist

### ISSUE THREAD

**Issue by intrigeri** [subgraph/oz#85]
Hi! On my GNOME Debian sid VM, `/media/$USER` does not exist yet for some reason. Presumably it would be created next time I plug in some removable storage device into that system, but whatever, so far it does not exist, which might be the case for various other kinds of new systems.

Starting Evince after having set up its sandbox with `oz-setup install evince` fails with:

<pre>
Oct 17 02:05:57 sid-desktop oz-daemon[2633]: 2016/10/17 02:05:57 [evince] Starting oz-init for profile: evince
Oct 17 02:05:57 sid-desktop org.gnome.Nautilus[2706]: ok received
Oct 17 02:05:57 sid-desktop oz-daemon[2633]: 2016/10/17 02:05:57 [evince] bind mounting (as readonly) /bin -> /srv/oz/rootfs/bin
Oct 17 02:05:57 sid-desktop oz-daemon[2633]: 2016/10/17 02:05:57 [evince] bind mounting (as readonly) /lib -> /srv/oz/rootfs/lib
Oct 17 02:05:57 sid-desktop oz-daemon[2633]: 2016/10/17 02:05:57 [evince] bind mounting (as readonly) /lib64 -> /srv/oz/rootfs/lib64
Oct 17 02:05:57 sid-desktop oz-daemon[2633]: 2016/10/17 02:05:57 [evince] bind mounting (as readonly) /usr -> /srv/oz/rootfs/usr
Oct 17 02:05:57 sid-desktop oz-daemon[2633]: 2016/10/17 02:05:57 [evince] bind mounting (as readonly) /etc -> /srv/oz/rootfs/etc
Oct 17 02:05:57 sid-desktop oz-daemon[2633]: 2016/10/17 02:05:57 [evince] Failed to setup filesytem: failed to create empty directory '/media/toto': stat /media/toto: no such file or directory
Oct 17 02:05:57 sid-desktop oz-daemon[2633]: 2016/10/17 02:05:57 Child process pid=4125 exited from daemon with status 1
</pre>

(my user is called "toto").

Then I've run `install -o toto -g toto -m 0755 -d /media/toto`, and could finally see oz running an app on a regular Debian system :)

**Comment by xSmurf** [comment]
Sadly things are more complicated than that. Debian uses xattrs on /media/* and not regular permissions. While it'll work if you create it as the user, your install will be non standard there after.

We've opted a while back that this was "not a bug", and fixed it at the distro level. I don't think we will revisit for now.

This is not properly related to #81.

**Comment by intrigeri** [comment]
> Sadly things are more complicated than that. Debian uses xattrs on /media/* and not regular permissions. While it'll work if you create it as the user, your install will be non standard there after.

OK, thanks for the explanation.

> We've opted a while back that this was "not a bug", and fixed it at the distro level.

OK, fair enough. This may be a blocker for integration into Debian and Tails though, so could you please point me to the code/configuration/whatever you use in SGOS to fix it?
