### ISSUE TITLE
Where is `syscalls_gen_args.go` ?

### ISSUE THREAD

**Issue by cpu** [subgraph/oz#87]
I can't seem to find the `syscalls_gen_args.go` program referenced in the top of [syscalls_args_amd64.go](https://github.com/subgraph/oz/blob/master/oz-seccomp/syscalls_args_amd64.go):
> // DO NOT EDIT. Autogenerated by syscalls_gen_args.go

Am I blind? :-) Where is this kept?

**Comment by dma** [comment]
You aren't blind. It's an ugly little program to parse syscall prototypes from kernel headers. It did an *OK* job, but I had to make many corrections to its incorrect argument type determinations over time. It was the kind of thing that needed to be run once and then it produced the static list of syscalls and arguments that we needed and then we didn't run it again. I wold be happy to share, I have to get it from backup. I can put it on Github. It was just not pretty, so I didn't..

**Comment by dma** [comment]
@cpu Yeah, syscalls_gen_args does what mksynum_linux.pl does, essentially. Sorry for the outrageously late reply!

**Comment by dma** [comment]
Will close this as I don't think we'll put the script back in. Ping me if you want it.

**Comment by cpu** [comment]
@dma Thanks for closing this! I forgot about it :-) No worries on the script - confirmation was enough. Thanks again
