### ISSUE TITLE
Can't copy onionshare URL via "Copy URL" button

### ISSUE THREAD

**Issue by dma** [subgraph/oz#90]
1. Click on "Copy URL" after hidden service setup
2. Try to paste anywhere: terminal, gedit, Tor Browser, etc

Trying to relaunchxpra doesn't seem to fix it. 

version of onionshare: 0.9.2
version of xpra: 0.17.6

**Comment by xSmurf** [comment]
oz-daemon log? I'm 99.99% this is a dupe of the xpra clipboard bug...
