### ISSUE TITLE
License compatibility

### ISSUE THREAD

**Issue by justincormack** [subgraph/oz#91]
The project LICENSE file is an MIT style license, but `gosecco` is AGPL licensed, see https://github.com/twtiger/gosecco/blob/master/LICENSE 

This makes the combined work AGPL licensed, making your license file somewhat misleading.

I previously asked about a license change for compatibility with Apache/MIT licensed projects but got a reply that this would not be changed https://github.com/twtiger/gosecco/issues/39

**Comment by dma** [comment]
Yes, this is an issue. Gosecco was actually developed *for* us by the TW team - we asked them to, and described what we needed, and they did an amazing job delivering that for our project and for the benefit of other projects out there. 

We started integrating it (IIRC) before it was even licensed presuming the license would be compatible. I personally don't understand the reason why the AGPL was chosen, and I'll have a conversation with the developers about that. If they're insistent on keeping the license we'll have to work around it.

**Comment by xSmurf** [comment]
Upstream has changed the license to LGPL 3.0! :tada:

Our vendored copy might not reflect this right away however.
