### ISSUE TITLE
Add creation of arbitrary symbolic links at sandbox creation

### ISSUE THREAD

**Issue by dma** [subgraph/oz#93]
One idea - bind symlinks to whitelisted (bind mounted paths)

Possibly a field in the whitelist entry, e.g.

	, {"path": "${XDG_DOWNLOAD_DIR}/Chrome", "can_create": true, "symlink": "${XDG_DOWNLOAD_DIR"}

**Comment by xSmurf** [comment]
Fixed by shared folder features. symlink remains unexposed to normal whitelist items but could be turned on if needed.
