### ISSUE TITLE
Oz client missing privilege checking

### ISSUE THREAD

**Issue by shw700** [subgraph/oz#96]
Currently, the oz client may be invoked by any user. This can lead to some nasty issues like X-based hangs if the user attempts to launch an oz sandboxed-application as root.
It seems that minimally, oz should reject invocations by (e)uid 0. But examining this issue at a deeper level might also reveal some deeper, more generic bug.

Other than rejecting oz client usage by root (perhaps the "list", "profiles" and "logs" sub-commands should be exempted), should any other user accounts be blacklisted? Or conversely, should the oz client interface only be usable the standard default "user" SGOS account?

**Comment by mckinney-subgraph** [comment]
```Or conversely, should the oz client interface only be usable the standard default "user" SGOS account?```
Whatever is decided about allowing or disallowing oz client usage by unprivileged users, we shouldn't hardcode "user" from SGOS. 

1. That doesn't work for any other OS 
2. The new installer (`calamares`) will most likely allow the user to choose their username

**Comment by shw700** [comment]
Sure, that totally makes sense. Of course this static configuration doesn't need to be enforced by the code, but could be picked up optionally from a configuration file, etc.

**Comment by xSmurf** [comment]
Closed in c15fff7
